<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46055" started-at="2018-10-28T22:53:29Z" finished-at="2018-10-28T22:54:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46055" started-at="2018-10-28T22:53:29Z" finished-at="2018-10-28T22:54:15Z">
      <class name="testcases.LaunchTheUrl">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.LaunchTheUrl@127bd23]" name="beforeSuite" is-config="true" duration-ms="1297" started-at="2018-10-28T22:53:28Z" finished-at="2018-10-28T22:53:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.LaunchTheUrl@127bd23]" name="setData" is-config="true" duration-ms="0" started-at="2018-10-28T22:53:29Z" finished-at="2018-10-28T22:53:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.LaunchTheUrl@127bd23]" name="beforeClass" is-config="true" duration-ms="0" started-at="2018-10-28T22:53:29Z" finished-at="2018-10-28T22:53:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.LaunchTheUrl@127bd23]" name="beforeMethod" is-config="true" duration-ms="36857" started-at="2018-10-28T22:53:29Z" finished-at="2018-10-28T22:54:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifysearch()[pri:0, instance:testcases.LaunchTheUrl@127bd23]" name="verifysearch" duration-ms="8400" started-at="2018-10-28T22:54:06Z" finished-at="2018-10-28T22:54:14Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at utils.Reporter.reportStep(Reporter.java:61)
at utils.Reporter.reportStep(Reporter.java:71)
at wdMethods.SeMethods.verifyDisplayed(SeMethods.java:303)
at pages.HomePage_RRS.verifysearchbutton(HomePage_RRS.java:24)
at testcases.LaunchTheUrl.verifysearch(LaunchTheUrl.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifysearch -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.LaunchTheUrl@127bd23]" name="afterMethod" is-config="true" duration-ms="703" started-at="2018-10-28T22:54:14Z" finished-at="2018-10-28T22:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:testcases.LaunchTheUrl@127bd23]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-10-28T22:54:15Z" finished-at="2018-10-28T22:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.LaunchTheUrl@127bd23]" name="afterSuite" is-config="true" duration-ms="1000" started-at="2018-10-28T22:54:15Z" finished-at="2018-10-28T22:54:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.LaunchTheUrl -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
